# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85dd2f22760884d5c65947e28cd114ad7c49bb98f15c030dbd77adaf0ae60565548246c1e8ef6a4d890df450105363177a3f217519bd0aae7b027bac4fbc49c6

test:
  secret_key_base: dc6a202aca7963bf1a3c29975c378afd677b1365b41ce6e9fe5e850beef20e951ea34d2de738c8b65548497b6f6c89a5a58a3582705cbb06b02cdc202c85aea8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
